import { Box, Img, Text } from '@chakra-ui/react';
import Head from 'next/head';
import Image from 'next/image';
import ErrorPage from '../components/section/ErrorPage';
import Intro from '../components/section/Intro';
import Mempelai from '../components/section/Mempelai';
import styles from '../styles/Home.module.css';
import { supabase } from '../utils/supabaseClient';
import dynamic from 'next/dynamic';

const DynamicMempelai = dynamic(() => import('../components/section/Mempelai'));
const Doa = dynamic(() => import('../components/section/Doa'));
const Event = dynamic(() => import('../components/section/Event'));
const Countdown = dynamic(() => import('../components/section/Countdown'));
const Story = dynamic(() => import('../components/section/Story'));
const Gallery = dynamic(() => import('../components/section/Gallery'));
const Guest = dynamic(() => import('../components/section/Guest'));

export default function Home({ guestId, data, error, status }) {
    if (error !== null) {
        return <ErrorPage message={'Error'} />;
    }

    console.log(data);

    const userTheme = {
        font_display: 'Playfair Display',
        font_display_url:
            'https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap',
        font_body: 'Josefin Sans',
        font_body_url:
            'https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,300;0,400;0,500;0,600;1,200;1,300;1,400&display=swap',
        text_light: '#FEFEFE',
        text_dark: '#527e60',
        text_semi: '#333745',
        bg_light: '#FEFEFE'
    };

    return (
        <Box bgColor='gray.800'>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='preconnect' href='https://fonts.googleapis.com' />
                <link
                    rel='preconnect'
                    href='https://fonts.gstatic.com'
                    crossOrigin='true'
                />
                <link href={userTheme.font_body_url} rel='stylesheet' />
                <link href={userTheme.font_display_url} rel='stylesheet' />
            </Head>
            <Box
                pos='relative'
                // w='full'
                mx='auto'
                // h='100vh'
                // minH='300vh'
                maxW='lg'
                scrollBehavior='smooth'
                d='flex'
                overflowX='hidden'
                flexDirection='column'
                fontFamily={userTheme.font_body}
                textColor={userTheme.text_semi}>
                <Intro data={data} theme={userTheme} />
                {/* <Box bg={'gray.300'} h='40' pos='relative'></Box> */}

                <DynamicMempelai data={data.people} theme={userTheme} />
                <Doa data={data.doa} theme={userTheme} />
                <Story data={data.story} theme={userTheme} />
                <Countdown data={data.date} theme={userTheme} />
                <Event data={data.event} theme={userTheme} />
                <Gallery data={data.gallery} theme={userTheme} />
                <Guest userId={data.id} guestId={guestId} theme={userTheme} />
            </Box>
        </Box>
    );
}

export async function getServerSideProps(context) {
    const query = context.query;
    const guestId = query.to;
    let { data, error, status } = await supabase
        .from('user_main')
        .select(
            `*, people:user_people(*), doa:user_doa(*), event:user_event(*), story:user_story(*), gallery:user_gallery(*)`
        )
        .eq('slug', query.pid)
        .order('gender', { foreignTable: 'user_people' })
        .single();
    // console.log(data);

    return {
        props: {
            data: data,
            error: error,
            status: status,
            guestId
        }
    };
}
